import * as React from "react";
import { Button } from "@islands/components/ui/button";
import { Textarea } from "@islands/components/ui/textarea";
import { Input } from "@islands/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@islands/components/ui/card";
import { api } from "@utils/api";
import { toast } from "sonner";

interface PlaceholderRow {
  key: string;
  value: string;
}

interface DocumentEditorProps {
  onPreviewGenerated: (
    pdfBlob: Blob,
    previewSignature: string,
    placeholders: Record<string, string>,
  ) => void;
}

export function DocumentEditor({ onPreviewGenerated }: DocumentEditorProps) {
  const [template, setTemplate] = React.useState(`# Document Title

This is a sample document template.

**Name:** {{name}}
**Date:** {{date}}

## Content

This document contains important information.

{{signature:{{name}}}}

---
*Generated by DocuChain*`);

  const [placeholders, setPlaceholders] = React.useState<PlaceholderRow[]>([
    { key: "name", value: "John Doe" },
    { key: "date", value: new Date().toLocaleDateString() },
  ]);
  const [isGenerating, setIsGenerating] = React.useState(false);

  const handleAddPlaceholder = () =>
    setPlaceholders((prev) => [...prev, { key: "", value: "" }]);

  const handleRemovePlaceholder = (index: number) => {
    setPlaceholders((prev) => prev.filter((_, i) => i !== index));
  };

  const handlePlaceholderChange = (
    index: number,
    field: "key" | "value",
    value: string,
  ) => {
    setPlaceholders((prev) => {
      const next = [...prev];
      next[index][field] = value;
      return next;
    });
  };

  const handleGeneratePreview = async () => {
    setIsGenerating(true);
    try {
      const placeholderObj: Record<string, string> = {};
      placeholders.forEach((row) => {
        if (row.key.trim()) {
          placeholderObj[row.key.trim()] = row.value;
        }
      });

      const { blob, headers } = await api.postBlob("/documents/preview", {
        template,
        placeholders: placeholderObj,
        metadata: {
          source: "web-ui",
          generated_at: new Date().toISOString(),
        },
      });

      const previewSignature =
        headers.get("X-Docuchain-Preview-Signature") || "";

      if (blob.type === "application/pdf") {
        onPreviewGenerated(blob, previewSignature, placeholderObj);
        toast.success("Preview generated successfully!");
      } else {
        const payload = await blob.text();
        try {
          const error = JSON.parse(payload);
          toast.error(error.error || "Failed to generate preview");
        } catch {
          toast.error("Failed to generate preview");
        }
      }
    } catch (error: any) {
      console.error("Error generating preview:", error);
      toast.error(error.message || "Failed to generate preview");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Document Template</CardTitle>
        <CardDescription>
          Enter Markdown with placeholders like {"{{name}}"} or {"{{date}}"} and
          use {"{{signature:name}}"} for signature slots.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <label className="text-sm font-medium mb-2 block">
            Template (Markdown)
          </label>
          <Textarea
            value={template}
            onChange={(event) => setTemplate(event.target.value)}
            className="min-h-[320px] font-mono text-sm"
            placeholder="# Your Document Title

Add your content here with placeholders like {{name}} or {{date}}.

{{signature:{{name}}}}"
          />
        </div>

        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-sm font-medium">Placeholders</label>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleAddPlaceholder}
            >
              Add Placeholder
            </Button>
          </div>
          <div className="space-y-2">
            {placeholders.map((placeholder, index) => (
              <div key={index} className="flex gap-2">
                <Input
                  placeholder="Key (e.g., name)"
                  value={placeholder.key}
                  onChange={(event) =>
                    handlePlaceholderChange(index, "key", event.target.value)
                  }
                  className="flex-1"
                />
                <Input
                  placeholder="Value"
                  value={placeholder.value}
                  onChange={(event) =>
                    handlePlaceholderChange(index, "value", event.target.value)
                  }
                  className="flex-1"
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => handleRemovePlaceholder(index)}
                >
                  ×
                </Button>
              </div>
            ))}
          </div>
        </div>

        <Button
          onClick={handleGeneratePreview}
          disabled={isGenerating}
          className="w-full"
        >
          {isGenerating ? "Generating Preview..." : "Generate Preview"}
        </Button>
      </CardContent>
    </Card>
  );
}
